const vcs = {
  title: "VC Survey",
  elements: [
    { type: "text", name: "name", title: "Name", isRequired: true },
    { type: "text", name: "email", title: "Email", isRequired: true },
    { type: "text", name: "phone", title: "Phone Number" },
    { type: "text", name: "firmName", title: "Firm Name", isRequired: true },
    {
      type: "checkbox",
      name: "investmentFocus",
      title: "Investment Focus/Strategy",
      choices: [
        "Early-stage startups",
        "Growth-stage startups",
        "Industry-specific investments",
        "Geography-specific investments",
      ],
    },
    {
      type: "checkbox",
      name: "industriesOfInterest",
      title: "Industries/Sectors of Interest",
      choices: [
        "Technology",
        "Healthcare",
        "Finance",
        "Education",
        "E-commerce",
        "Energy",
        "Real estate",
        "Other",
      ],
    },
    {
      type: "text",
      name: "investmentSize",
      title: "Typical Investment Size",
      inputType: "number",
    },
    {
      type: "checkbox",
      name: "preferredCompanyStage",
      title: "Preferred Company Stage",
      choices: [
        "Seed",
        "Series A",
        "Series B",
        "Series C and beyond",
        "Pre-IPO",
        "IPO and beyond",
      ],
    },
    {
      type: "comment",
      name: "portfolioCompanies",
      title: "Portfolio Companies (if applicable)",
      placeHolder: "Separate company names with commas",
    },
    {
      type: "checkbox",
      name: "preferredMetric",
      title: "Preferred Key Metric",
      choices: [
        "Monthly Recurring Revenue (MRR)",
        "Customer Acquisition Cost (CAC)",
        "Customer Lifetime Value (LTV)",
        "Churn Rate",
        "Gross Margin",
      ],
    },
  ],
};

const founders = {
  title: "Founder Survey",
  elements: [
    { type: "text", name: "name", title: "Name", isRequired: true },
    { type: "text", name: "email", title: "Email", isRequired: true },
    { type: "text", name: "phone", title: "Phone Number" },
    {
      type: "text",
      name: "title",
      title: "Founder's Title",
      isRequired: true,
    },
    {
      type: "text",
      name: "startupName",
      title: "Startup Name",
      isRequired: true,
    },
    { type: "text", name: "website", title: "Website" },
    { type: "text", name: "location", title: "Location", isRequired: true },
    {
      type: "checkbox",
      name: "industry",
      title: "Industry/Sector",
      choices: [
        "Technology",
        "Healthcare",
        "Finance",
        "Education",
        "E-commerce",
        "Energy",
        "Real estate",
        "Other",
      ],
      isRequired: true,
    },
    {
      type: "text",
      name: "fundingRaised",
      title: "Funding Raised (USD)",
      inputType: "number",
    },
    {
      type: "radiogroup",
      name: "fundingStage",
      title: "Funding Stage",
      choices: [
        "Pre-seed",
        "Seed",
        "Series A",
        "Series B",
        "Series C and beyond",
      ],
    },
    {
      type: "comment",
      name: "pitch",
      title: "Briefly describe your startup (1-2 sentences)",
      maxLength: 280,
      isRequired: true,
    },
    {
      type: "text",
      name: "mrr",
      title: "Monthly Recurring Revenue (MRR) (USD)",
      inputType: "number",
    },
    {
      type: "text",
      name: "cac",
      title: "Customer Acquisition Cost (CAC) (USD)",
      inputType: "number",
    },
    {
      type: "text",
      name: "ltv",
      title: "Customer Lifetime Value (LTV) (USD)",
      inputType: "number",
    },
    {
      type: "text",
      name: "churnRate",
      title: "Churn Rate (in %)",
      inputType: "number",
    },
    {
      type: "text",
      name: "grossMargin",
      title: "Gross Margin (in %)",
      inputType: "number",
    },
    {
      type: "text",
      name: "fundingAmount",
      title: "How much money do you need?",
      inputType: "number",
    },
    {
      type: "radiogroup",
      name: "creditScore",
      title: "How's your credit score?",
      choices: [
        "500 or below",
        "500-575",
        "575-650",
        "650-680",
        "680-720",
        "720-760",
        "760+",
      ],
    },
    {
      type: "radiogroup",
      name: "bankruptcy",
      title: "Have you had a bankruptcy in the last 5 Years?",
      choices: ["Yes", "No"],
    },
    {
      type: "text",
      name: "businessStart",
      title: "When did you start your business?",
    },
    {
      type: "file",
      name: "dataRequest2",
      title: "Actual P&L, BS, and CF statements on a monthly basis in an excel spreadsheet for the past 24 months. Please make sure S&M, R&D and G&A include payroll and salaries. If not, please provide payroll and salaries expenses breakdown by each department (S&M, R&D, G&A, etc.)",
      accept: ".xlsx, .xls",
    },
    {
      type: "file",
      name: "dataRequest3a",
      title: "Revenue by client: Please provide a spreadsheet with sales data by a customer for the past 36 months that reconcile to the P&L with the following fields: Date, Client ID/ Name, Amount, Currency, and Revenue Stream.",
      accept: ".xlsx, .xls",
    },
    {
      type: "file",
      name: "dataRequest3b",
      title: "Revenue by client: Alternatively, please provide an invoices file that includes all invoices issued in the past 36 months, that reconcile to the financial statements. Invoice file spreadsheet should include – date, Invoice ID, unique Customer ID (that will enable to identify each client separately and not by the payment method such as Shopify/ Stripe/ PayPal/ etc.), Amount paid, currency, Invoice type or revenue stream (Monthly/quarterly/annually, other, etc.).",
      accept: ".xlsx, .xls",
    },
    {
      type: "file",
      name: "dataRequest4",
      title: "Monthly /Quarterly consolidated business plan including P&L and CF statements in an excel spreadsheet for the upcoming 4 years (48 months). Please make sure it is consistent with the historical P&L and CF provided so far.",
      accept: ".xlsx, .xls",
    },
    {
      type: "text",
      name: "dataRequest5",
      title: "Up-to-date cap table.",
    },
    {
      type: "file",
      name: "dataRequest6",
      title: "Historical funding rounds – please provide a table including information regarding the historical funding rounds – including for each round the raised amount, name of round (A, B, CLA, etc.), date, pre-money valuation, and main investors participating in each round.",
      accept: ".xlsx, .xls",
    },
    {
      type: "file",
      name: "dataRequest7",
      title: "Audited financials - Please provide the last 2 (or more) audited reports.",
      accept: ".pdf",
    },
    {
      type: "text",
      name: "dataRequest8",
      title: "Debt (if relevant) - Please specify the main terms – current debt outstanding, type (LOC or term loan), when taken, repayments schedule, interest, total facility amount, amounts withdrawn to date, any liens regarding this facility, or any other liens on the company's assets.",
    },
    {
      type: "text",
      name: "dataRequest9",
      title: "Group structure – please provide a full group structure, including the country of incorporation of each entity, and revenue allocations between the entities.",
    },
    {
      type: "text",
      name: "additional1",
      title: "Who is the end customer (b2",
    },
    {
      type: "text",
      name: "additional2",
      title: "What is the Business model (contractual, subscription… )",
    },

  ],
};

export { vcs, founders };
